"$schema" = 'config-schema.json'

format = """
[](primary)\
$os\
$username\
[](fg:primary bg:primary_container)\
$directory\
[](fg:primary_container bg:secondary)\
$git_branch\
$git_status\
[](fg:secondary bg:secondary_container)\
$c\
$cpp\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:secondary_container bg:tetriary)\
$docker_context\
$conda\
$pixi\
[](fg:tetriary)\
$fill\
[](fg:tetriary)\
$time\
[ ](fg:tetriary)\
$line_break$character"""

palette = 'matugen-colors'

[palettes.matugen-colors]
surface_container = '#14140c'
on_surface_container = '#e6e3d5'

primary = '#cbcb76'
on_primary = '#323200'

primary_container = '#494900'
on_primary_container = '#e7e78f'

secondary = '#cac8a5'
on_secondary = '#323218'

secondary_container = '#48482d'
on_secondary_container = '#e6e4bf'

tetriary = '#a4d0bd'
on_tetriary = '#0b372a'

tetriary_container = '#254e40'
on_tetriary_container = '#bfecd9'

error = '#ffb4ab'
on_error = '#690005'

[os]
disabled = false
style = "bg:primary fg:on_primary"

[os.symbols]
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
AOSC = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[username]
show_always = true
style_user = "bg:primary fg:on_primary"
style_root = "bg:primary fg:"
format = '[ $user ]($style)'

[directory]
style = "bg:primary_container fg:on_primary_container"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:secondary"
format = '[[ $symbol $branch ](fg:on_secondary bg:secondary)]($style)'

[git_status]
style = "bg:color_aqua"
format = '[[($all_status$ahead_behind )](fg:on_secondary bg:secondary)]($style)'

[nodejs]
symbol = "󰎙"
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:on_secondary_container bg:secondary_container)]($style)'

[c]
symbol = " "
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:on_secondary_container bg:secondary_container)]($style)'

[cpp]
symbol = " "
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:on_secondary_container bg:secondary_container)]($style)'

[rust]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:on_secondary_container bg:secondary_container)]($style)'

[golang]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:on_secondary_container bg:secondary_container)]($style)'

[php]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:on_secondary_container bg:secondary_container)]($style)'

[java]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:on_secondary_container bg:secondary_container)]($style)'

[kotlin]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:on_secondary_container bg:secondary_container)]($style)'

[haskell]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:on_secondary_container bg:secondary_container)]($style)'

[python]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:on_secondary_container bg:secondary_container)]($style)'

[docker_context]
symbol = ""
style = "bg:color_bg3"
format = '[[ $symbol( $context) ](fg:on_tetriary bg:tetriary)]($style)'

[conda]
style = "bg:color_bg3"
format = '[[ $symbol( $environment) ](fg:on_tetriary bg:tetriary)]($style)'

[pixi]
style = "bg:color_bg3"
format = '[[ $symbol( $version)( $environment) ](fg:on_tetriary bg:tetriary)]($style)'

[fill]
symbol = " "

[time]
disabled = false
time_format = "%R"
style = "bg:tetriary"
format = '[[  $time ](fg:on_tetriary bg:tetriary)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:primary)'
error_symbol = '[](bold fg:error)'
vimcmd_symbol = '[](bold fg:primary)'
vimcmd_replace_one_symbol = '[](bold fg:secondary)'
vimcmd_replace_symbol = '[](bold fg:secondary)'
vimcmd_visual_symbol = '[](bold fg:tetriary)'
